### ISSUE TITLE
Passing options to `http2.connect`

### ISSUE THREAD

**Issue by pietermees** [grantila/fetch-h2#10]
It seems that the current implementation is not passing the options along to `session.get`, which means they're not reaching the `http2.connect` call.

See https://github.com/grantila/fetch-h2/blob/master/lib/fetch.ts#L231

**Comment by grantila** [comment]
That's right, but that's because these options aren't available in the Fetch API (which in itself is version agnostic, so has no H2-specific options).

What could be done, is to add this to the `context`. Which options specifically are you missing?

**Comment by pietermees** [comment]
I resolved this for myself by passing `init` as a second argument on the line I mentioned. Some of the options I'm trying to pass are:
- `settings` to override the H2 settings like `maxConcurrentStreams`
- `lookup` to provide a custom DNS lookup function
- `key`, `cert` and `rejectUnauthorized` to accept self-signed SSL certificates (we use this to run local SSL tests)

**Comment by grantila** [comment]
Which won't compile, because these are two different types. These options you want, I'll look into adding it to the *context* instead, so that it's a one-time setup and then all `fetch` requests get it transparently.
I'll have a look at this shortly.

**Comment by pietermees** [comment]
Oh, I'm sorry, I'm not familiar with TypeScript. I spliced the change to `dist` and that worked.
Thanks for looking into it!
