### ISSUE TITLE
Error: No valid exports main found for '.../already'

### ISSUE THREAD

**Issue by sooxt98** [grantila/fetch-h2#103]
![image](https://user-images.githubusercontent.com/13378059/80870513-811a5580-8cd9-11ea-8256-29e4d32c424b.png)

**Comment by grantila** [comment]
Unable to reproduce, you need to share what your code is doing.

Just running `yarn add fetch-h2` and running this, works fine for me:

```
const {fetch} = require('fetch-h2');

async function f(){
    const res = await fetch("https://google.com");
    const body = await res.text();
}
f();
```
