### ISSUE TITLE
Not working node v14.2.0

### ISSUE THREAD

**Issue by sharper** [grantila/fetch-h2#104]
fetch-h2 v2.4.5. not working in node v14.2.0.
default options , and in the end TimeoutError: timed out after 10000 ms

**Comment by joshbalfour** [comment]
experiencing the same

**Comment by masx200** [comment]
https://github.com/grantila/fetch-h2/issues/102

**Comment by masx200** [comment]
https://github.com/sindresorhus/got/issues/1172

**Comment by joshbalfour** [comment]
@masx200 thanks for the pointer - switched to got@master and all's good across node 13 and 14!

**Comment by Blitss** [comment]
Same for the node@13.14.0. http2 doesn't work (http/2+quic/46)

**Comment by niklaskorz** [comment]
Node v12.17 seems to be broken as well, which is particularly weird because apparently the Node devs backported breaking changes to a minor update of an LTS release?
Downgrading to v12.16.3 seems to work.

**Comment by mgabeler-lee-6rs** [comment]
Anyone have insight on what nodejs commits broke/fixed this so we can request them to be reverted in / backported to 12.x?
