### ISSUE TITLE
Fix synchronous session connection

### ISSUE THREAD

**Issue by pietermees** [grantila/fetch-h2#15]
Due to https://github.com/nodejs/node/issues/19839, the `http2Connect` callback at https://github.com/grantila/fetch-h2/blob/4321b063b84f08d7c2741c338adb5e6802493b80/lib/context.ts#L214 doesn't get called if the session synchronously connected.

**Comment by grantila** [comment]
Good catch. I'll wait for an upstream fix as of now.

**Comment by pietermees** [comment]
Fixed by https://github.com/nodejs/node/pull/19842
