### ISSUE TITLE
Handle all (relevant) Http2Stream events

### ISSUE THREAD

**Issue by grantila** [grantila/fetch-h2#4]
As said in #1, there are Http2Stream events currently not handled. There are different reasons for all of them to not yet having been handled, this is my current thoughts:

 * [x] [`aborted`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_aborted)
   * Will this also invoke `error`, i.e. could we ignore this?
 * [x] [`frameError`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_frameerror_1)
   * Same
 * [x] [`timeout`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_timeout_1)
   * Same
 * [ ] [`trailers`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_trailers)
   * AFAIK, these can occur after [`response`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_response), which is when the promise is resolved and `fetch()` is complete (not the body data necessarily). If this should be handled at all, we'd need an optional callback in the options argument to `fetch()` so that the user can get these trailing headers. Implementation logic (such as cookies) are [not allowed](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Trailer) to be sent, so `fetch-h2` won't internally need to care about these headers.
 * [x] [`continue`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_continue)
   * The Fetch API clearly [forbids](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name) the `Expect` header to be sent in a request, so 100 shouldn't be a valid response. This event should probably reject the flow as it *can't* happen.
 * [x] [`headers`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_headers)
   * I'm not sure why a user of `fetch()` would ever expect a 1xx response, this is usually a set of low-level handshakes. I don't think this should be handled other than perhaps a rejected promise (at least not for now).

Thoughts on this @pranaygp?

**Comment by grantila** [comment]
Only trailers left. The rest are failure now, they shouldn't happen. Will keep open until trailers are completely implemented.

**Comment by pranaygp** [comment]
Whoops, sorry for not responding to this earlier.

I agree with the optional argument in the fetch call for `trailers`. something like `handleTrailers` might be intuitive? Definitely seems intuitive to me.

I also don't think I completely understand how `continue` works (will need to read up about this). 

With `headers` is it possible to receive a valid response after receiving a `1xx` response? If not, then yeah, rejecting might make sense.

In general, It's likely fine to reject a promise as long as we're providing a user some way to identify which one of these things happened from the error object they receive in `.catch`

**Comment by grantila** [comment]
Or `onTrailers`? Semantics, but still. Perhaps just `trailers`. We already have `onPush`.

You're right, it would be very useful to be able to [specifically](https://github.com/grantila/already#specific) catch these errors, so that their constructors must be public. I'll fix that.

Won't close this until all these issues are well defined and documented.

**Comment by grantila** [comment]
`timeout` and `aborted` errors will be handled in #6. Other errors are rare and are pure `Error`'s. Should likely never happen anyway.

**Comment by pranaygp** [comment]
That makes sense.

I wonder if `frameError` is a valid error that could be the client's fault, and not the backend?,

**Comment by pranaygp** [comment]
In any case, yeah, `frameError` should rejected the promise with an `Error`. I think the implementation is correct

**Comment by grantila** [comment]
By the way, @pranaygp, you mentioned the `body` handling previously, this is changed in #5, so now you can send any string, buffer and readable stream as `{body}`, and a helper `{json}` for objects that should be sent as JSON (with `application/json` automatically set).

**Comment by pranaygp** [comment]
I noticed that, and was actually just reading the changes

I don't think `getStringOrBufferOrReadableStream` is a good name though
(from the README)
How does fetch handle this? Can we just have a single `body` property in
the object that takes a string, or array buffer or stream. And then, the
user can just add `content-type: application/json` to the headers if they
want to.

That way we can completely get rid of constructors the user needs to
invoke, and stay closer to `fetch`

**Comment by grantila** [comment]
That's exactly how it's done now, maybe I was unclear in the docs, I'll update it. I meant that you can assign these types to `body` directly.

**Comment by grantila** [comment]
😎 https://github.com/grantila/fetch-h2/commit/bf5028f4000f07add75c3a7b64580603ce873410
