### ISSUE TITLE
use multi wild-domains cert, got error

### ISSUE THREAD

**Issue by sharper** [grantila/fetch-h2#92]
multi wild-domains cert,  SAN:   *.domain1.com, *.domain2.com
when use fetch-h2 access site (such as:  www.domain2.com ) 
 using multi wild-domains cert  will got error:
Error: unable to verify the first certificate.

**Comment by grantila** [comment]
Which version of fetch-h2 is this, and do you have a certificate to share?

This looks more like your CA is not trusted. Is it self-signed? Then you need to allow self-signed certificates. In either case, look here for the discussion: https://stackoverflow.com/questions/31673587/error-unable-to-verify-the-first-certificate-in-nodejs
This is not fetch-h2 related per se.

If you want to [allow self-signed certs](https://github.com/grantila/fetch-h2#low-level-session-configuration), do:
```
setup( { session: { rejectUnauthorized: false } } );
```
before doing any `fetch( )`.

**Comment by sharper** [comment]
san.js 31
name.match(/.*\*.*\*.*/)  
if  subject.CN like:  *.domain1.com,*.domain2.com  
will throw exception:  Invalid CN/subjectAltNames

**Comment by grantila** [comment]
Do you have a certificate I can test with? Doesn't look right, you can't have multiple names in subject.CN, you need to use SAN, so the error is correct.

**Comment by sharper** [comment]
Our a server crt,  CN="*.wanscloud.com,*.ajyun.com.cn,*.ajcloud.net"
and SAN = DNS: wanscloud.com, DNS:*.wanscloud.com, DNS:....  

[Subject]
  E=support@ajcloud.net, CN="*.wanscloud.com,*.ajyun.com.cn,*.ajcloud.net", OU=Ajcloud Certification Authority, O="Nanjing Ajcloud Infotech Co., Ltd", C=CN

**Comment by grantila** [comment]
Is this a valid certificate, to have multiple comma-separated domains (wildcard or not) in the CN fields? I don't think you're allowed to.

The CN (afaik) should only contain one domain, and the rest (including that in the CN) should be in the SAN.

Also, if you have a SAN, the [CN can be ignored](https://stackoverflow.com/questions/5935369/ssl-how-do-common-names-cn-and-subject-alternative-names-san-work-together), although fetch-h2 doesn't ignore it - it would be allowed to ignore it.

Is this certificate created by a trusted well-known CA? Are browsers like Chrome and Firefox accepting it?

**Comment by sharper** [comment]
YES
 the self-signed certification can accepted by Chrome and Firefox , Microsoft Edge.

**Comment by sharper** [comment]
CN contains one domain,  I also see other certs. 
I think to re-sign the cert,  BUT all services should restart.
